# Site settings
title: Urban Savasana
email: nikolspencer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creating in the Chaos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nikolspencer.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalinks: pretty
