# Site settings
title: Urban Savasana
email: nikolspencer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Creating in the Chaos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nikolspencer.github.io" # the base hostname & protocol for your site
twitter_username: nikolspencer
github_username: nikolspencer

# Build settings
markdown: kramdown
